general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/reactor-dpms.sh on
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = ~/.config/hypr/reactor-dpms.sh off
    on-resume = ~/.config/hypr/reactor-dpms.sh on
}
