# ☢ REACTOR — kitty theme (included from kitty.conf)
font_family        JetBrainsMono Nerd Font
font_size          12.0
background         #040e03
background_opacity 0.90
foreground         #39ff14
cursor             #39ff14
cursor_text_color  #000000
cursor_shape       block
cursor_blink_interval 0.5
selection_background #39ff14
selection_foreground #000000
url_color          #9dff80

window_padding_width 14
active_border_color   #39ff14
inactive_border_color #1f8f0b

color0  #040e03
color8  #1f8f0b
color1  #ff2a2a
color9  #ff5c5c
color2  #39ff14
color10 #9dff80
color3  #ffb000
color11 #ffd35c
color4  #1f8f0b
color12 #58d63a
color5  #7dff5c
color13 #b8ffa6
color6  #2bd9a0
color14 #7affd0
color7  #b8ffa6
color15 #e6ffe0
