#!/usr/bin/env bash
# ☢ REACTOR — installer
#
# Links everything under dotfiles/ into ~/.config (same relative paths), backs up
# anything it replaces, then wires up fish, kitty and Hyprland with small,
# reversible additions. Safe to run again at any time.
#
#   bash install.sh                       # normal install / update
#   bash install.sh --with-hyprland-conf  # also link the full classic hyprland.conf
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
DOT="$ROOT_DIR/dotfiles"
CFG="$HOME/.config"
STAMP="$(date +%Y%m%d-%H%M%S)"
WITH_HYPR_CONF=0
for arg in "$@"; do
  case $arg in
    --with-hyprland-conf) WITH_HYPR_CONF=1 ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
  esac
done

G=$'\e[38;2;57;255;20m'; D=$'\e[38;2;31;143;11m'; A=$'\e[38;2;255;176;0m'; R=$'\e[0m'
say()  { printf '%s☢%s %s\n' "$G" "$R" "$*"; }
note() { printf '  %s%s%s\n' "$D" "$*" "$R"; }
warn() { printf '  %s⚠ %s%s\n' "$A" "$*" "$R"; }

backup() {  # copy a real file aside before we touch it
  [[ -e $1 && ! -L $1 ]] && cp -a "$1" "$1.backup-$STAMP" && note "backed up ${1/#$HOME/~}"
  return 0
}

link_file() {  # link_file <repo source> <target>
  local src=$1 dst=$2
  mkdir -p "$(dirname "$dst")"
  if [[ -L $dst && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then return; fi
  if [[ -e $dst || -L $dst ]]; then
    mv "$dst" "$dst.backup-$STAMP"
    note "backed up ${dst/#$HOME/~}"
  fi
  ln -s "$src" "$dst"
}

say "Installing REACTOR dotfiles from ${ROOT_DIR/#$HOME/~}"

# ---------------------------------------------------------------- 1. clean up old links
# Earlier versions of this repo linked files that no longer exist (wlogout,
# fastfetch, nuclear.rasi …). Remove links into this repo that now point nowhere.
while IFS= read -r -d '' l; do
  t=$(readlink "$l")
  if [[ $t == "$ROOT_DIR"/* && ! -e $t ]]; then rm "$l"; note "removed stale link ${l/#$HOME/~}"; fi
done < <(find "$CFG" -maxdepth 4 -type l -print0 2>/dev/null)

# ---------------------------------------------------------------- 2. link dotfiles
chmod +x "$DOT"/waybar/scripts/*.sh "$DOT"/eww/reactor/scripts/* "$DOT"/reactor/*.sh "$DOT"/hypr/*.sh

while IFS= read -r -d '' f; do
  rel=${f#"$DOT"/}
  case $rel in
    hypr/hyprland.conf) (( WITH_HYPR_CONF )) || continue ;;
    kitty/kitty.conf)   [[ -e $CFG/kitty/kitty.conf || -L $CFG/kitty/kitty.conf ]] && \
                        [[ "$(readlink -f "$CFG/kitty/kitty.conf")" != "$f" ]] && continue ;;
  esac
  link_file "$f" "$CFG/$rel"
done < <(find "$DOT" -type f -print0)
note "linked waybar · rofi · eww · kitty · btop · hyprlock · hypridle · terminal"

# old single-file installs left a plain 'config' that would override config.jsonc
[[ -f $CFG/waybar/config && ! -L $CFG/waybar/config ]] && mv "$CFG/waybar/config" "$CFG/waybar/config.backup-$STAMP"

# ---------------------------------------------------------------- 3. kitty
if [[ -L $CFG/kitty/kitty.conf ]]; then :   # using our full kitty.conf
elif ! grep -qs "reactor-kitty.conf" "$CFG/kitty/kitty.conf"; then
  backup "$CFG/kitty/kitty.conf"
  printf '\n# ☢ REACTOR theme\ninclude reactor-kitty.conf\n' >> "$CFG/kitty/kitty.conf"
  note "added theme include to kitty.conf"
fi

# ---------------------------------------------------------------- 4. fish
if command -v fish >/dev/null; then
  fishrc="$CFG/fish/config.fish"
  mkdir -p "$CFG/fish"; touch "$fishrc"
  if grep -qE '^[[:space:]]*fastfetch' "$fishrc" || ! grep -q "reactor/reactor.fish" "$fishrc"; then
    backup "$fishrc"
  fi
  # the REACTOR greeting replaces fastfetch (commented out, not deleted)
  sed -i -E 's/^([[:space:]]*)(fastfetch.*)$/\1# \2  # disabled by REACTOR/' "$fishrc"
  grep -q "reactor/reactor.fish" "$fishrc" || \
    printf '\n# ☢ REACTOR prompt + greeting (keep this last)\nsource ~/.config/reactor/reactor.fish\n' >> "$fishrc"
  rm -f "$CFG/fish/conf.d/reactor.fish"   # from a very early version
else
  warn "fish not found — the REACTOR prompt and greeting are fish-only"
fi

# ---------------------------------------------------------------- 5. Hyprland
TOGGLE='~/.config/eww/reactor/scripts/toggle.sh'
DAEMON='eww -c ~/.config/eww/reactor daemon'

# classic snippet (used by hyprland.conf setups and our optional full config)
cat > "$CFG/hypr/reactor.conf" <<EOF
# ☢ REACTOR — generated by Custom-Linux-Waybar/install.sh (safe to delete)
bind = SUPER, Z, exec, $TOGGLE
exec-once = $DAEMON
layerrule = animation slide left, reactor-sidebar
EOF

if [[ -f $CFG/hypr/hyprland.lua ]]; then
  lua="$CFG/hypr/hyprland.lua"
  if grep -qE 'eww/reactor|reactor-sidebar|^-- ☢ REACTOR sidebar' "$lua" || ! grep -q "hypr/reactor.lua" "$lua"; then
    backup "$lua"
  fi
  # remove lines appended by older REACTOR installers (avoids a double Super+Z)
  sed -i -e '/eww\/reactor\/scripts\/toggle.sh/d' -e '/eww\/reactor daemon/d' \
         -e '/reactor-sidebar/d' -e '/^-- ☢ REACTOR/d' "$lua"
  # match the key style your own binds use ("SUPER + Q" vs "SUPER+Q")
  combo="SUPER + Z"; grep -qE 'hl\.bind\("[A-Z_]+\+[A-Za-z0-9]' "$lua" && combo="SUPER+Z"
  cat > "$CFG/hypr/reactor.lua" <<EOF
-- ☢ REACTOR — generated by Custom-Linux-Waybar/install.sh (safe to delete)
-- Every line is wrapped in pcall so a future API change can never break your config.
pcall(function() hl.bind("$combo", hl.dsp.exec_cmd("$TOGGLE")) end)
pcall(function() hl.exec_cmd("$DAEMON") end)
pcall(function() hl.layer_rule({ match = { namespace = "reactor-sidebar" }, animation = "slide left" }) end)
EOF
  grep -q "hypr/reactor.lua" "$lua" || \
    printf '\n-- ☢ REACTOR (keep this last)\npcall(dofile, os.getenv("HOME") .. "/.config/hypr/reactor.lua")\n' >> "$lua"
  note "Hyprland (Lua): Super+Z sidebar + slide animation"
elif (( WITH_HYPR_CONF )); then
  note "Hyprland: using the full REACTOR hyprland.conf"
elif [[ -f $CFG/hypr/hyprland.conf ]]; then
  if ! grep -q "hypr/reactor.conf" "$CFG/hypr/hyprland.conf"; then
    backup "$CFG/hypr/hyprland.conf"
    sed -i -e '/eww\/reactor\/scripts\/toggle.sh/d' -e '/eww\/reactor daemon/d' -e '/reactor-sidebar/d' "$CFG/hypr/hyprland.conf"
    printf '\n# ☢ REACTOR\nsource = ~/.config/hypr/reactor.conf\n' >> "$CFG/hypr/hyprland.conf"
  fi
  note "Hyprland (classic): Super+Z sidebar + slide animation"
else
  warn "no Hyprland config found — add Super+Z yourself: $TOGGLE"
fi

# ---------------------------------------------------------------- 6. wallpaper
WALL_DIR="$HOME/Pictures/Wallpapers"
mkdir -p "$WALL_DIR"
cp -n "$ROOT_DIR/wallpapers/reactor-core-4k.png" "$WALL_DIR/" 2>/dev/null || true
if command -v swww >/dev/null && swww query >/dev/null 2>&1; then
  swww img "$WALL_DIR/reactor-core-4k.png" --transition-type grow >/dev/null 2>&1 && note "wallpaper set (swww)"
else
  note "wallpaper copied to ~/Pictures/Wallpapers/reactor-core-4k.png"
fi

# ---------------------------------------------------------------- 7. restart pieces
eww -c "$CFG/eww/reactor" kill >/dev/null 2>&1 || true
rm -f "${XDG_RUNTIME_DIR:-/tmp}/reactor-eww.open"
command -v eww >/dev/null && (eww -c "$CFG/eww/reactor" daemon >/dev/null 2>&1 &)
if command -v waybar >/dev/null; then
  pkill -x waybar 2>/dev/null || true
  (setsid -f waybar >/dev/null 2>&1 &)
fi

# ---------------------------------------------------------------- 8. what's missing
need=()
for pair in waybar:waybar rofi:rofi eww:eww kitty:kitty fish:fish socat:socat \
            checkupdates:pacman-contrib powerprofilesctl:power-profiles-daemon \
            wpctl:wireplumber pavucontrol:pavucontrol bluetoothctl:bluez-utils \
            nvidia-smi:"" tailscale:tailscale; do
  cmd=${pair%%:*} pkg=${pair#*:}
  if ! command -v "$cmd" >/dev/null && [[ -n $pkg ]]; then need+=("$pkg"); fi
done
fc-list 2>/dev/null | grep -qi "JetBrainsMono Nerd" || need+=(ttf-jetbrains-mono-nerd)

echo
say "${G}REACTOR ONLINE${R}"
if (( ${#need[@]} )); then
  warn "missing packages: ${need[*]}"
  note "install with:  sudo pacman -S --needed ${need[*]}"
fi
if [[ ! -r /sys/class/powercap/intel-rapl:0/energy_uj ]]; then
  note "CPU watts in the sidebar are locked by default. To show them (optional):"
  note "  sudo cp $ROOT_DIR/system/reactor-rapl.conf /etc/tmpfiles.d/ && sudo systemd-tmpfiles --create"
fi
note "Reload Hyprland (or log out/in) for Super+Z, then open a new kitty window."
